"""initial

Revision ID: d0b47cafb024
Revises: 
Create Date: 2026-03-01 20:53:54.088907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b47cafb024'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=True),
    sa.Column('purchase_datetime', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('imported', 'needs_review', 'matched', 'applied', name='receiptstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=True),
    sa.Column('pattern_type', sa.Enum('contains', 'regex', name='patterntype'), nullable=True),
    sa.Column('pattern_value', sa.String(length=500), nullable=True),
    sa.Column('suggested_subcategory', sa.String(length=100), nullable=True),
    sa.Column('ynab_category_id', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ynab_access_token_enc', sa.Text(), nullable=True),
    sa.Column('ynab_refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('ynab_budget_id', sa.String(length=100), nullable=True),
    sa.Column('ynab_account_id', sa.String(length=100), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('receipt_id', sa.String(length=36), nullable=True),
    sa.Column('ynab_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('request_json', sa.Text(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('description_raw', sa.String(length=500), nullable=True),
    sa.Column('description_normalized', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('total_price_cents', sa.Integer(), nullable=True),
    sa.Column('category_suggestion', sa.String(length=100), nullable=True),
    sa.Column('rule_hit', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_proposal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('ynab_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('proposal_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ynab_link',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('ynab_budget_id', sa.String(length=100), nullable=True),
    sa.Column('ynab_account_id', sa.String(length=100), nullable=True),
    sa.Column('ynab_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('matched_amount_cents', sa.Integer(), nullable=True),
    sa.Column('matched_date', sa.Date(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id'),
    sa.UniqueConstraint('ynab_transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ynab_link')
    op.drop_table('split_proposal')
    op.drop_table('receipt_item')
    op.drop_table('audit_log')
    op.drop_table('settings')
    op.drop_table('rule')
    op.drop_table('receipt')
    # ### end Alembic commands ###
